### ISSUE TITLE
Mutating original polygon

### ISSUE THREAD

**Issue by ThomasG77** [Turfjs/turf-flip#4]
Try below to see what seems abnormal :
you are mutating `poly` whereas if you assigned `flip` function result to a new variable `flipped`, your intent seems to mean `poly` should not mutate.

    var flip = require('turf-flip')
    var polygon = require('turf-polygon')

    var poly = polygon([[[1,0], [1,0], [1,2]], [[.2,.2], [.3,.3],[.1,.2]]])

    var flipped = flip(poly)

    console.log(flipped.geometry.coordinates);
    console.log(poly.geometry.coordinates);

Issue seems related to Turfjs/turf#116

**Comment by lyzidiamond** [comment]
This is happening with points, too! Still an issue.

**Comment by tmcw** [comment]
Fixed in 6f833bb7909071246f1222ef874d4a4208f486a7
